# Generated by Django 3.2.3 on 2021-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jobrole', models.CharField(max_length=30)),
                ('qual', models.CharField(max_length=30)),
                ('spes', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
