# Generated by Django 3.2.3 on 2021-05-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date',
            new_name='ApplyDate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='qual',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='Salary',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='spes',
            new_name='Specialisation',
        ),
    ]
